spring:
  application:
    title: Spring Boot
    version: v3.1.11
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/school_assigment
    username: panhaserey
    password: nha@12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
    open-in-view: false
  mail:
    host: localhost
    port: 1025
    username: user
    password: user12345
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  liquibase:
    default-schema: public
    enabled: true
    change-log: 'classpath:/db/changelog/db.changelog-master.yaml'
server:
  port: 8181
  servlet:
    context-path: /api/v1
springdoc:
  default-produces-media-type: application/json
  packagesToScan: com.school.project
  swagger-ui:
    path: /swagger-ui
  api-docs:
    enabled: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:3000/activate-account
  api:
    version: 1